// <auto-generated />
using LabaVrode.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabaVrode.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250206234314_popa")]
    partial class popa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("LabaVrode.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ключ");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Имя_пользователя");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Пароль");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Является_Администратором");

                    b.HasKey("Id");

                    b.ToTable("Пользователи");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "123",
                            isAdmin = true
                        },
                        new
                        {
                            Id = 2,
                            Login = "user1",
                            Password = "321",
                            isAdmin = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
